# Generated by Django 5.2.8 on 2026-03-01 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_rename_device_id_devices_device_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='device_type',
            new_name='device_id',
        ),
    ]
