# Generated by Django 5.2.8 on 2026-03-01 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_rename_device_type_devices_device_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='device_id',
            new_name='device_type_id',
        ),
    ]
