# Generated by Django 5.2.8 on 2026-03-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_rename_device_id_devices_device_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='status',
        ),
    ]
