# Generated by Django 5.2.8 on 2026-01-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='timestamp',
        ),
    ]
