# Generated by Django 5.2.8 on 2025-12-11 09:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebugLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
        ),
    ]
