# Generated by Django 5.2.8 on 2026-02-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debug', '0002_alter_debuglog_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debuglog',
            old_name='message',
            new_name='payload',
        ),
        migrations.RemoveField(
            model_name='debuglog',
            name='log_type',
        ),
        migrations.AddField(
            model_name='debuglog',
            name='response',
            field=models.TextField(default='Development Test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debuglog',
            name='topic',
            field=models.TextField(default='Development Test'),
            preserve_default=False,
        ),
    ]
