# Generated by Django 5.2.8 on 2026-01-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='threshold_max_value',
            field=models.CharField(default=100, max_length=30),
        ),
        migrations.AddField(
            model_name='sensors',
            name='threshold_min_value',
            field=models.CharField(default=1, max_length=30),
        ),
    ]
