# Generated by Django 5.2.8 on 2026-01-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_sensors_threshold_max_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='threshold_max_value',
            field=models.DecimalField(decimal_places=3, default=100, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='threshold_min_value',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
    ]
