# Generated by Django 5.2.8 on 2026-01-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_alter_sensors_threshold_max_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='status',
            field=models.CharField(default='active', max_length=30),
        ),
    ]
