# Generated by Django 5.2.8 on 2026-03-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_sensors_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='buffer_size',
            field=models.DecimalField(decimal_places=3, default=50, max_digits=10),
        ),
    ]
