# Generated by Django 5.2.8 on 2026-03-01 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_sensors_buffer_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensors',
            old_name='device_id',
            new_name='device_type',
        ),
    ]
