# Generated by Django 5.2.8 on 2026-03-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_rename_device_type_sensors_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensors',
            name='status',
        ),
        migrations.AddField(
            model_name='sensors',
            name='active_timeout',
            field=models.DecimalField(decimal_places=3, default=500, max_digits=10),
        ),
    ]
