# Generated by Django 5.2.8 on 2026-03-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0008_remove_sensors_status_sensors_active_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50),
            preserve_default=False,
        ),
    ]
