# Generated by Django 5.2.8 on 2026-03-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0009_sensors_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensors',
            name='status',
        ),
    ]
