# Generated by Django 5.2.8 on 2026-02-24 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0004_sensors_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_data', models.DecimalField(decimal_places=1, default='unknown', max_digits=30)),
                ('device_id', models.IntegerField(default=2)),
                ('max_threshold', models.DecimalField(decimal_places=1, default='unknown', max_digits=30)),
                ('min_threshold', models.DecimalField(decimal_places=1, default='unknown', max_digits=30)),
                ('alert_type', models.CharField(default='unknown', max_length=100)),
                ('status', models.CharField(default='critical', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.sensors')),
            ],
        ),
    ]
