# Generated by Django 5.2.8 on 2026-01-06 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerts',
            name='threshold',
        ),
    ]
