# Generated by Django 5.2.8 on 2026-02-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='sensor_type',
            field=models.CharField(default='unknown', max_length=30),
        ),
    ]
