# Generated by Django 5.2.8 on 2026-01-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_remove_alerts_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerts',
            name='alert_type',
        ),
        migrations.AddField(
            model_name='alerts',
            name='alert_msg',
            field=models.CharField(default='critical', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alerts',
            name='status',
            field=models.CharField(default='not_resolved', max_length=30),
        ),
    ]
