# Generated by Django 5.2.8 on 2026-03-01 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alerts_sensor_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerts',
            old_name='device_id',
            new_name='device_type',
        ),
    ]
