# Generated by Django 5.2.8 on 2026-02-22 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_remove_alerts_alert_type_alerts_alert_msg_and_more'),
        ('data', '0002_remove_data_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='sensor_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.data'),
        ),
    ]
